name: Reusable - Build

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      node-version:
        required: false
        type: string
      java-version:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: inputs.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version || '18' }}
          cache: 'npm'

      - name: Install Dependencies (Node)
        if: inputs.language == 'node'
        run: npm ci

      - name: Build (Node)
        if: inputs.language == 'node'
        run: npm run build

      - name: Setup Java
        if: inputs.language == 'java'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version || '17' }}
          distribution: 'temurin'

      - name: Build (Maven)
        if: inputs.language == 'java'
        run: mvn clean install -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            target/
